# Analysis single stock market price using yfinance module

In [ ]:
# Upgrade the module 
# Ref: https://stackoverflow.com/questions/68320184/yfinance-returning-error-when-downloading-data
#!pip install yfinance --upgrade --no-cache-dir

In [1]:
import yfinance as yf
import pandas as pd

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Set any float number precision 2 decimal points
pd.set_option('precision', 2)

In [2]:
start_date = '2016-01-01'
end_date = '2021-09-15'

In [3]:
# Extract stock price only 'Adj Close' and 'Volume'

df = yf.download('AAPL',start=start_date,end=end_date,interval='1d',rounding=1)[['Adj Close', 'Volume']]#.to_frame()

[*********************100%***********************]  1 of 1 completed

In [4]:
df.head(3)

            Adj Close     Volume
Date
2015-12-31      24.27  163649200
2016-01-04      24.29  270597600
2016-01-05      23.68  223164000

In [5]:
# Define function for style
def above_zero(val):
  color = 'green' if val > 0 else 'red'
  return 'color: %s' % color

In [6]:
# Copy file to prevent A value is trying to be set on a copy of a slice from a DataFrame
df = df.copy()

# Find Adjusted Close price percentage
df.loc[:,'AdjC_pct'] = df.loc[:,'Adj Close'].pct_change()*100

# Fill NaN value with zero
df.fillna(value = 0, inplace = True)

### Find typical price change %

In [7]:
df['AdjC_pct'].value_counts(bins = 5)

(-2.92, 2.051]      1233
(2.051, 7.021]       132
(-7.89, -2.92]        59
(7.021, 11.991]        7
(-12.886, -7.89]       5
Name: AdjC_pct, dtype: int64

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
Stock price typically change between -2.92% to 2%.
</div>

In [8]:
# Highlight column 'AdjC_pct' and put bar on 'Volume'
df.sample(3).style.applymap(above_zero, subset=['AdjC_pct'])\
.bar(subset = ['Volume'])\
.format({'Adj Close': "{:.2f}",'AdjC_pct': "{:.2f}",'AdjC_cum': "{:.2f}"})\
.highlight_max()

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
High volume transaction is an indication of price %change quite significant ↓ (or ↑) (might relate with any issue).
</div>

In [9]:
# Create list of days category
dayscat = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# Create list of months category
monthscat = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

### Check typical % change in monthly basis

In [10]:
# Groupby months name → find average → highlight on volume
df.groupby(df.index.month_name()).mean().reindex(monthscat).style.applymap(above_zero, subset=['AdjC_pct'])\
.format({'Adj Close': "{:.2f}",\
         'Volume': "{:.0f}",\
         'AdjC_pct': "{:.2f}",\
         'AdjC_cum': "{:.2f}"})\
.bar(subset = ['Volume'])

In [11]:
# Set pivot table based segregate based on year and month name, then calculate the mean aggregate
df2 = df.pivot_table(index=df.index.year,
                     columns = df.index.month_name(),
                     fill_value = 0,
                     aggfunc = {'AdjC_pct':'mean'})

# Remove the first multi index column 
df2.columns = df2.columns.droplevel(0)

# Re-index based on monthscat
df2 = df2.reindex(columns=monthscat)

In [12]:
df2.style.applymap(above_zero).background_gradient(cmap='RdYlGn_r')

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
1. July and August is the month with highest % price change.<br/>
2. September is the month with lowest % price change.<br/>
3. January is the month with highest volume transaction.<br/>
4. July is the month with lowest volume transaction.<br/>
</div>

### Check typical % change in daily basis

In [13]:
# Groupby days name → find average → highlight on volume → set precision
df.groupby(df.index.day_name()).mean().reindex(dayscat).style\
.bar(subset = ['Volume'])\
.format({'Adj Close': "{:.2f}",\
         'Volume': "{:.0f}",\
         'AdjC_pct': "{:.2f}",\
         'AdjC_cum': "{:.2f}"})

In [14]:
# Set pivot table based segregate based on year and month name, then calculate the mean aggregate
df3 = df.pivot_table(index=df.index.year,
                     columns = df.index.day_name(),
                     fill_value = 0,
                     aggfunc = {'AdjC_pct':'mean'})

# Remove the first multi index column 
df3.columns = df3.columns.droplevel(0)

# Re-index based on monthscat
df3 = df3.reindex(columns=dayscat)

# Fill NaN value with zero
df3.fillna(value = 0, inplace = True)

# Apply style
df3.style.applymap(above_zero).background_gradient(cmap='RdYlGn_r')

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
1. Monday is the highest % price change.<br/>
2. Thursday is the lowest % price change.<br/>
3. Friday is the day with highest volume transaction.<br/>
4. Thursday is the day with lowest volume transaction.<br/>
</div>

### Check typical % change in week basis in a month

In [15]:
# Groupby weekday → find average → highlight on volume → set precision
df.groupby(df.index.weekday).mean().style.applymap(above_zero, subset=['AdjC_pct'])\
.bar(subset = ['Volume'])\
.format({'Adj Close': "{:.2f}",\
         'Volume': "{:.0f}",\
         'AdjC_pct': "{:.2f}",\
         'AdjC_cum': "{:.2f}"})

In [16]:
# Set pivot table based segregate based on year and weekday name, then calculate the mean aggregate
df4 = df.pivot_table(index=df.index.month_name(),
                     columns = df.index.weekday,
                     aggfunc = {'AdjC_pct':'mean'})

# Remove the first multi index column 
df4.columns = df4.columns.droplevel(0)

# Re-index based on monthscat
df4 = df4.T.reindex(columns=monthscat)

# Fill NaN value with zero
df4.fillna(value = 0, inplace = True)

# Apply style
df4.style.applymap(above_zero).background_gradient(cmap='RdYlGn_r')

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
1. Mostly first week in every month is the highest % price change.<br/>
2. Mostly last week in every month is the lowest % price change.<br/>
3. Last week in a month typically record extreme max & min of volume transaction.<br/>
</div>

### Check typical % change in date basis

In [17]:
# Groupby day name → find average → highlight on volume → set precision
df.groupby(df.index.day).mean().style.applymap(above_zero, subset=['AdjC_pct'])\
.bar(subset = ['Volume'])\
.format({'Adj Close': "{:.2f}",\
         'Volume': "{:.0f}",\
         'AdjC_pct': "{:.2f}",\
         'AdjC_cum': "{:.2f}"})

In [18]:
# Set pivot table based segregate based on year and month name, then calculate the mean aggregate
df5 = df.pivot_table(index=df.index.year,
                     columns = df.index.day,
                     fill_value = 0,
                     aggfunc = {'AdjC_pct':'mean'})

# Remove the first multi index column 
df5.columns = df5.columns.droplevel(0)

# Apply style
df5.T.style.applymap(above_zero).background_gradient(cmap='RdYlGn_r')

<div class="alert alert-block alert-info">
<b>Key insight:<br/> 
1. Day 1 and Day 15 is the highest % price change.<br/>
2. Day 19 and Day 27 is the lowest % price change.<br/>
3. Day 31 is the day with highest volume transaction.<br/>
4. Day 22 is the day with lowest volume transaction.<br/>
</div>

### Key Takeaway

<div class="alert alert-block alert-success">

General finding:<br/>
1. Stock price typically % change between -2.92% to 2%.<br/>

From month perspective:<br/>
2. July and August seems the best month to harvest the profit.<br/>
3. September seems the best month to buy the stock (lowest % price change).<br/>

From day perspective:<br/>
4. Monday is the highest % price change.<br/>
5. Thursday seems the best day to buy the stock (lowest % price change).<br/> 

From week in a month perspective:<br/>
6. Mostly first week in every month is the highest % price change.<br/>
7. Mostly last week in every month seems the best week to buy the stock (lowest % price change).<br/> 

From date perspective:<br/>
8. Day 1 and Day 15 is the highest % price change.<br/>
9. Day 19 and Day 27 probably the best date to buy the stock (lowest % price change).<br/>
</div>